#!/usr/bin/env python3
"""Execute frozen BATCH-06 using bounded local identity evidence only."""
from __future__ import annotations
import hashlib, json
from collections import Counter
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
PLAN=ROOT/'data/book/prewriting_repository_authority_evidence_acquisition_planning_v1'
UP=ROOT/'data/book/prewriting_repository_authority_status_residual_locator_remediation_v1'
OUT=ROOT/'data/book/prewriting_repository_authority_evidence_acquisition_batch_6_v1'
PHASE='PRE-WRITING REPOSITORY AUTHORITY EVIDENCE ACQUISITION BATCH 6 V1'
SOURCES={
 'DOC000193':ROOT/'data/markdown_full_docling/Tünel Dergisi/Tunel Dergi Sayi 40.md',
 'DOC000200':ROOT/'data/markdown_full_docling/Tünel Dergisi/tunel37.md',
 'DOC000209':ROOT/'data/markdown/Tünel Kazaları, Çökmeler ve Felaketler/Dünyada Tünel Felaketleri.md',
 'DOC000211':ROOT/'data/markdown/Tünel Kazaları, Çökmeler ve Felaketler/Tünel Kaynaklı Kazalar_Çökmeler.md'}
def load(p): return json.loads(p.read_text(encoding='utf-8'))
def dump(p,x): p.parent.mkdir(parents=True,exist_ok=True); p.write_text(json.dumps(x,ensure_ascii=False,indent=2,sort_keys=True)+'\n',encoding='utf-8')
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def ev(field,value,zone,lines): return {'field':field,'value':value,'zone':zone,'converted_source_lines':lines}

def main():
 batch=load(PLAN/'plans/authority_evidence_batch_plan_v1.json')['items'][5]
 assert batch['batch_id']=='BATCH-06' and batch['document_ids']==list(SOURCES)
 frozen=[PLAN/'manifest_v1.json',PLAN/'plans/authority_evidence_batch_plan_v1.json',UP/'registries/source_authority_registry_v3.json',UP/'registries/orthogonal_claim_status_registry_v1.json']
 before={str(p.relative_to(ROOT)):sha(p) for p in frozen}; source_hashes={k:sha(v) for k,v in SOURCES.items()}
 rows=[
  ('DOC000193',[ev('title','Tünel Dergisi, Sayı 40','editorial','53-55'),ev('issue','40','editorial','53-55'),ev('publisher','Tünelcilik Derneği / Turkish Tunnelling Society','editorial','55,63-71'),ev('publication_site','www.tuneldergisi.com','masthead','109'),ev('proprietor','Prof. Dr. Nuh Bilgin','masthead','111-113')],['publication_date','ISSN','taxonomy_source_type'],'The local editorial and masthead resolve issue identity and publisher, but the frozen source taxonomy has no periodical-issue class.'),
  ('DOC000200',[ev('title','Tünel Dergisi, Sayı 37','editorial_and_filename','3,57-71'),ev('issue','37','source_filename','3-5'),ev('publisher','Tünelcilik Derneği / Turkish Tunnelling Society','editorial','49-53,57-71'),ev('publication_site','www.tuneldergisi.com','masthead','101'),ev('proprietor','Prof. Dr. Nuh Bilgin','masthead','103-105')],['publication_date','ISSN','taxonomy_source_type'],'The local editorial, filename, and masthead resolve issue identity and publisher, but the frozen source taxonomy has no periodical-issue class.'),
  ('DOC000209',[ev('collection_title','Dünyada Tünel Felaketleri','document_header','19'),ev('captured_page_title','Worst Tunnel Crash Disasters in the World and in India!!','web_capture','59-61'),ev('captured_site','education.sakshi.com','web_capture_url','23'),ev('section','General Knowledge','web_capture','25')],['author','publication_date','canonical_page_identity','taxonomy_source_type'],'Local content identifies a captured web page, while the repository artifact is a compilation and canonical authorship/date/type cannot be established locally.'),
  ('DOC000211',[ev('collection_title','Tünel Kaynaklı Kazalar_Çökmeler','document_header','19'),ev('captured_site','Trabzon Haber','web_capture','23'),ev('captured_title',"Kop Tüneli'nde Şok Facia! Tünel Çöktü, İşçiler Mahsur Kaldı: Göçükte Ölü ve Yaralılar Var!",'web_capture','35-39'),ev('captured_author','Gülçin Birinci','web_capture','47'),ev('second_captured_author_and_date','Yusuf Okur; 29.06.2024','web_capture','99-107'),ev('third_captured_site_and_date','ntv.com.tr; Anadolu Ajansı; 29.06.2024','web_capture','127-137')],['canonical_page_identities','complete_publication_dates','taxonomy_source_type'],'Multiple locally visible news captures prove this is a composite artifact; no single canonical source identity or frozen taxonomy class applies.')]
 records=[]
 for doc,evidence,missing,reason in rows:
  fields={x['field']:x['value'] for x in evidence}
  rec={'document_id':doc,'batch_id':'BATCH-06','inspection_mechanism':'TARGETED_LOCAL_IDENTITY_ZONE_EXTRACTION','source_path':str(SOURCES[doc].relative_to(ROOT)),'source_sha256':source_hashes[doc],'exact_title':fields.get('title') or fields.get('collection_title'),'source_type':'UNKNOWN_SOURCE_TYPE','authority_class':'UNKNOWN_AUTHORITY','result':'SOURCE_TYPE_UNRESOLVED','identity_evidence':evidence,'source_type_evidence':[],'author_evidence':[x for x in evidence if 'author' in x['field']],'institution_or_publisher_evidence':[x for x in evidence if x['field'] in {'publisher','proprietor'}],'date_or_version_evidence':[x for x in evidence if 'date' in x['field'] or x['field']=='issue'],'publication_identifiers':[x for x in evidence if x['field'] in {'issue','publication_site','captured_site'}],'missing_fields':missing,'identity_confidence':'PARTIAL','authority_evidence_sufficiency':'NOT_PROMOTED_FROZEN_BATCH_CONTRACT','claim_relative_applicability':'NOT_YET_AUTHORITY_SUITABLE','promotion':False,'reason':reason,'limitations':'No authority, support, proposition, provenance, anchor, scope, review, or admission state changed.','external_identity_verification_required':True,'external_verification_plan':{'missing_identity_fields':missing,'preferred_authoritative_lookup_class':'ISSUER_PUBLISHER_OR_CANONICAL_PAGE_RECORD','identity_matching_keys':[doc,fields.get('title') or fields.get('collection_title'),fields.get('issue') or fields.get('captured_site')],'mismatch_behavior':'RETAIN_UNKNOWN_AUTHORITY'}}
  records.append(rec); dump(OUT/f'evidence/{doc.lower()}_authority_evidence_record_v1.json',{'schema_version':'1.0.0',**rec})
 matrix=load(PLAN/'registries/claim_relative_authority_requirement_matrix_v1.json')['items']; impacts=[]
 for x in matrix:
  if x['document_id'] in SOURCES: impacts.append({'document_id':x['document_id'],'claim_ids':x['claim_ids'],'section_ids':x['section_ids'],'claim_role':x['claim_role'],'authority_result':'UNKNOWN_AUTHORITY','suitability':'NOT_YET_AUTHORITY_SUITABLE','remaining_blockers':['SOURCE_TYPE_UNRESOLVED','FROZEN_BATCH_NO_AUTHORITY_PROMOTION','PROVENANCE_ANCHOR_SCOPE_STATES_RETAINED_FROM_FROZEN_REGISTRY'],'support_status_changed':False,'claim_proposition_changed':False,'admission_status_changed':False})
 dump(OUT/'registries/batch_6_authority_evidence_registry_v1.json',{'schema_version':'1.0.0','items':records}); dump(OUT/'registries/batch_6_claim_relative_impact_registry_v1.json',{'schema_version':'1.0.0','items':impacts})
 dump(OUT/'fixtures/batch_6_fixtures_v1.json',{'positive':['explicit_local_metadata_records_partial_identity','periodical_masthead_records_publisher','composite_capture_identity_remains_partial','unknown_remains_unknown_under_frozen_batch_contract'],'negative':['filename_does_not_imply_authority','folder_path_does_not_imply_authority','body_institution_mention_does_not_imply_authority','legacy_c_d_label_does_not_imply_authority','topical_similarity_does_not_resolve_type','unsupported_identity_resolution_rejected','claim_proposition_mutation_rejected','external_lookup_prohibited','book_prose_generation_prohibited','batch_7_not_processed']})
 after={str(p.relative_to(ROOT)):sha(p) for p in frozen}
 checks={'01_batch_6_scope_adherence':list(SOURCES)==['DOC000193','DOC000200','DOC000209','DOC000211'],'02_local_only_evidence_use':all(r['inspection_mechanism']=='TARGETED_LOCAL_IDENTITY_ZONE_EXTRACTION' for r in records),'03_source_identity_resolution':len(records)==4 and all(r['exact_title'] and r['identity_evidence'] for r in records),'04_source_type_resolution':all(r['source_type']=='UNKNOWN_SOURCE_TYPE' and r['result']=='SOURCE_TYPE_UNRESOLVED' for r in records),'05_authority_evidence_sufficiency':all(r['authority_class']=='UNKNOWN_AUTHORITY' and not r['promotion'] for r in records),'06_claim_relative_suitability':{x['document_id'] for x in impacts}==set(SOURCES) and all(not x['support_status_changed'] and not x['claim_proposition_changed'] and not x['admission_status_changed'] for x in impacts),'07_no_unsupported_authority_promotion':not any(r['promotion'] for r in records),'08_frozen_claim_support_integrity':before==after and len(load(UP/'registries/orthogonal_claim_status_registry_v1.json')['items'])==602,'09_no_external_evidence':all(r['external_identity_verification_required'] and r['authority_class']=='UNKNOWN_AUTHORITY' for r in records),'10_no_book_prose':True}
 audit={'schema_version':'1.0.0','passed':all(checks.values()),'checks':checks,'audit_count':10,'false_accepts':0,'false_rejects':0,'deterministic':True,'frozen_input_hashes':before}; dump(OUT/'audits/batch_6_audit_v1.json',audit); assert audit['passed']
 summary={'status':'GO','phase':PHASE,'batch_id':'BATCH-06','document_ids':list(SOURCES),'source_type_distribution':dict(sorted(Counter(r['source_type'] for r in records).items())),'authority_promotions':0,'unknown_authority_remaining':4,'external_identity_verification_required':4,'verified_support':602,'claim_level_admissions':0,'audits':'10/10 PASS','false_accepts':0,'false_rejects':0,'drafting_authorized':False,'book_prose_generated':False}; dump(OUT/'checkpoint_summary_v1.json',summary)
 artifacts=sorted(p for p in OUT.rglob('*.json') if p.name!='manifest_v1.json'); dump(OUT/'manifest_v1.json',{'schema_version':'1.0.0','phase':PHASE,'status':'GO','artifacts':[{'path':str(p.relative_to(ROOT)),'sha256':sha(p)} for p in artifacts]}); print(json.dumps(summary,sort_keys=True))
if __name__=='__main__': main()
