#!/usr/bin/env python3
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data/book/prewriting_audit"
OUT.mkdir(parents=True, exist_ok=True)

def load(path):
    return json.loads((ROOT / path).read_text())

def write(name, value):
    path = OUT / name
    path.write_text(json.dumps(value, ensure_ascii=False, indent=2) + "\n")
    return path

def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()

structure = load("data/book/master_structure/book_master_structure_v1.json")
scope = load("data/book/scope_contracts/section_scope_boundary_contracts_v1.json")
coverage = load("data/book/coverage/corpus_to_book_coverage_mapping_v1.json")
research = load("data/book/research/research_question_gap_registry_v1.json")
assets = load("data/book/assets/nontext_asset_policy_registry_v1.json")
editorial = load("data/book/editorial/editorial_mechanics_v1.json")
packets = load("data/book/evidence_packets/section_evidence_packets_v1.json")

dimensions = [
    (1, "master structure completeness", "PASS", "7 chapters; 60/60 explicit sections"),
    (2, "structural fidelity to user outline", "PASS", "invented/deleted headings 0/0"),
    (3, "author/responsibility preservation", "HOLD", "supplied authors preserved; unresolved responsibility decisions remain"),
    (4, "scope/boundary completeness", "HOLD", "60/60 contracts; seven boundaries await human approval"),
    (5, "corpus coverage", "HOLD", "28 WEAK; 32 UNOBSERVED; validated primary sources 0"),
    (6, "research-question completeness", "PASS", "60/60 sections"),
    (7, "evidence-gap visibility", "PASS", "all known gaps explicit"),
    (8, "terminology readiness", "PASS_WITH_ADVISORY", "Swelling Rock fallback safely preserved unresolved"),
    (9, "notation readiness", "PASS", "notation contract frozen"),
    (10, "citation/bibliography readiness", "HOLD", "mechanics frozen; claim-level validated evidence absent"),
    (11, "cross-reference readiness", "PASS", "67 stable IDs; collisions 0"),
    (12, "visual/table/chart/equation readiness", "HOLD", "60/60 plans; evidence availability unvalidated"),
    (13, "cost-analysis methodology readiness", "HOLD", "base-year, conversion and dataset evidence unresolved"),
    (14, "history/current-information freshness readiness", "HOLD", "freshness unresolved pending evidence admission"),
    (15, "section packet completeness", "PASS", "60/60 packets"),
    (16, "unresolved human decisions", "HOLD", "boundary, responsibility and hierarchy decisions remain"),
    (17, "state synchronization", "PASS", "CP8 active at audit execution"),
    (18, "frozen artifact integrity", "PASS", "CP1–CP7 manifests hash-listed"),
    (19, "no manuscript prose generated by this orchestrator", "PASS", "book prose generated false"),
    (20, "no hidden transition into drafting", "PASS", "drafting authorized false")
]

blockers = [
    {"blocker_id": "PWB-001", "area": "evidence", "finding": "No claim-level validated primary evidence is admitted; coverage is 28 WEAK and 32 UNOBSERVED.", "remediation_route": "versioned evidence admission and coverage remediation"},
    {"blocker_id": "PWB-002", "area": "human decisions", "finding": "Seven scope boundaries and chapter/section responsibility or hierarchy decisions remain unresolved.", "remediation_route": "human decision closure"},
    {"blocker_id": "PWB-003", "area": "cost analysis", "finding": "Cost dataset provenance, base year, conversions and derived-metric methodology are not evidence-ready.", "remediation_route": "versioned cost-methodology readiness closure"},
    {"blocker_id": "PWB-004", "area": "freshness", "finding": "Historical/current/statistical claims have no completed freshness review.", "remediation_route": "versioned freshness and evidence-admission review"},
    {"blocker_id": "PWB-005", "area": "non-text assets", "finding": "Asset plans exist, but evidence availability and rights status have not been validated.", "remediation_route": "versioned asset evidence and rights review"}
]

advisories = [
    {"advisory_id": "PWA-001", "finding": "Keep Swelling Rock as the visible original-language fallback until an authoritative Turkish term is approved."},
    {"advisory_id": "PWA-002", "finding": "Treat redundant strength-class/unit wording as advisory unless it creates technical ambiguity."}
]

human = []
for rule in scope["boundary_rules"]:
    human.append({"decision_id": rule["rule_id"], "type": "BOUNDARY", "affected_ids": rule["section_ids"], "state": rule["status"]})
for i, exc in enumerate(scope["responsibility_exceptions"], 1):
    human.append({"decision_id": f"RESP-{i:03d}", "type": "RESPONSIBILITY", "affected_ids": exc["section_ids"], "state": exc["state"]})
for i, item in enumerate(scope["chapter_level_unresolved_decisions"], 1):
    human.append({"decision_id": f"CHDEC-{i:03d}", "type": "CHAPTER_STRUCTURE_OR_RESPONSIBILITY", "affected_ids": [], "state": item})
human.append({"decision_id": "TERM-P0008-ROCK-SWELLING", "type": "TERMINOLOGY", "affected_ids": [], "state": "ORIGINAL_TERM_UNRESOLVED_WITH_SAFE_FALLBACK"})

matrix = []
for packet in packets["packets"]:
    matrix.append({
        "section_id": packet["section_id"],
        "source_title": packet["source_title"],
        "coverage_status": packet["evidence"]["coverage_status"],
        "readiness": packet["readiness"]["state"],
        "drafting_authorized": False
    })

decision = "PRE-WRITING_HOLD"
audit = {
    "checkpoint": "CP8 — BOOK-WIDE PRE-WRITING AUDIT V1",
    "decision": decision,
    "dimensions": [{"dimension": n, "name": name, "status": status, "evidence": evidence} for n, name, status, evidence in dimensions],
    "dimension_count": len(dimensions),
    "blocker_count": len(blockers),
    "book_prose_generated": False,
    "drafting_authorized": False
}
recommendation = {
    "decision": decision,
    "next_phase": "PRE-WRITING FAILURE ANALYSIS V1",
    "instruction": "Analyze and sequence the five registered blockers without authorizing drafting.",
    "drafting_authorized": False
}

core = {
    "book_wide_prewriting_audit_v1.json": audit,
    "prewriting_readiness_matrix_v1.json": {"section_count": len(matrix), "sections": matrix},
    "prewriting_blocker_register_v1.json": {"count": len(blockers), "blockers": blockers},
    "prewriting_advisory_register_v1.json": {"count": len(advisories), "advisories": advisories},
    "prewriting_human_decision_register_v1.json": {"count": len(human), "decisions": human},
    "prewriting_next_step_recommendation_v1.json": recommendation
}
core_paths = [write(name, value) for name, value in core.items()]

source_manifests = [
    "data/book/master_structure/book_master_structure_v1_manifest.json",
    "data/book/scope_contracts/section_scope_boundary_contracts_v1_manifest.json",
    "data/book/coverage/corpus_to_book_coverage_mapping_v1_manifest.json",
    "data/book/research/research_question_gap_registry_v1_manifest.json",
    "data/book/assets/nontext_asset_policy_registry_v1_manifest.json",
    "data/book/editorial/editorial_mechanics_v1_manifest.json",
    "data/book/evidence_packets/section_evidence_packets_v1_manifest.json"
]
acceptance = ROOT / "data/book/prewriting_audit/contracts/book_wide_prewriting_audit_v1_acceptance.json"
hash_entries = [{"path": str(p.relative_to(ROOT)), "sha256": sha(p)} for p in [acceptance] + [ROOT / p for p in source_manifests] + core_paths]
hash_path = write("prewriting_hash_list_v1.json", {"algorithm": "SHA-256", "files": hash_entries})
manifest = {
    "artifact": "book_wide_prewriting_audit_v1",
    "status": "FROZEN / PRE-WRITING_HOLD",
    "decision": decision,
    "files": hash_entries + [{"path": str(hash_path.relative_to(ROOT)), "sha256": sha(hash_path)}],
    "drafting_authorized": False
}
write("frozen_prewriting_manifest_v1.json", manifest)
